### ISSUE TITLE
mcm parser value değeri

### ISSUE THREAD

**Issue by brcoztn** [hadikrkc/CS576-Agile-Software-Development#3]
mcm parser da okunan ıdlerin doğru fakat kontrolü target state tab'ında yapılacak.
![mcmsmarttv](https://cloud.githubusercontent.com/assets/22853814/20257578/82b23872-aa5b-11e6-90e4-e79aff37414c.PNG)

**Comment by huseyinorsan** [comment]
ok. Çözüldü.
