### ISSUE TITLE
yeni eklenen classlara unit test eklenmesi

### ISSUE THREAD

**Issue by brcoztn** [hadikrkc/CS576-Agile-Software-Development#4]
ModelUpdate.cs classı hariç diğer classlar için unit testler oluşturulabilir.

**Comment by hadikrkc** [comment]
Xml parsing fonksiyonu için bir test yazıldı,,

**Comment by brcoztn** [comment]
@hadikrkc @gonuldsk @Ibrahim1899 yeni eklenen classlar ve fonksiyonların testleri yazılabilir.
