### ISSUE TITLE
Sample Feature create and calculate spending time

### ISSUE THREAD

**Issue by brcoztn** [hadikrkc/CS576-Agile-Software-Development#7]
Open http://www.splot-research.org/
edit an existing Model
Create new feature 
calculate spending time
@hadikrkc @huseyinorsan @gonuldsk @Ibrahim1899

**Comment by brcoztn** [comment]
3 sample feature has created.
And noted the spending time calculate.

**Comment by huseyinorsan** [comment]
ok feature ler eklendi

**Comment by gonuldsk** [comment]
2 sample feature has created.
And noted the spending time calculate.

**Comment by Ibrahim1899** [comment]
Feature 1 added & updated creation time

**Comment by Ibrahim1899** [comment]
Feature 2-3 added & updated creation time

**Comment by hadikrkc** [comment]
3 model için süre hesabı yapıldı.
